// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260124160825_AddedDeckListField")]
    partial class AddedDeckListField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.BinderCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("QuantityToTrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TradeBinderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("TradeBinderId");

                    b.ToTable("BinderCards");
                });

            modelBuilder.Entity("Core.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtCrop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BackImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAltered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMisprint")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("double precision");

                    b.Property<string>("PurchasePriceCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Core.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfCards")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Core.Models.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("CurrentBranchId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentCommitId")
                        .HasColumnType("integer");

                    b.Property<string>("DeckList")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfCards")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfMainBoardCards")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfSideBoardCards")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<int?>("TotalPriceCurrency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentBranchId");

                    b.HasIndex("CurrentCommitId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Core.Models.DeckBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<int?>("HeadCommitId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HeadCommitId");

                    b.HasIndex("DeckId", "Name")
                        .IsUnique();

                    b.ToTable("DeckBranches");
                });

            modelBuilder.Entity("Core.Models.DeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtCrop")
                        .HasColumnType("text");

                    b.Property<string>("BackImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("CollectorNumber")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaindeckQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OwnedCardId")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .HasColumnType("text");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetName")
                        .HasColumnType("text");

                    b.Property<int>("SideboardQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("TypeLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("OwnedCardId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("Core.Models.DeckCommit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("TreeId");

                    b.ToTable("DeckCommits");
                });

            modelBuilder.Entity("Core.Models.DeckCommitParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommitId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentCommitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommitId");

                    b.HasIndex("CommitId", "ParentCommitId")
                        .IsUnique();

                    b.ToTable("DeckCommitParents");
                });

            modelBuilder.Entity("Core.Models.DeckTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("TreeHash")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("DeckTrees");
                });

            modelBuilder.Entity("Core.Models.DeckTreeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaindeckQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SideboardQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("TreeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TreeId", "ScryfallId")
                        .IsUnique();

                    b.ToTable("DeckTreeEntries");
                });

            modelBuilder.Entity("Core.Models.TradeBinder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TradeBinders");
                });

            modelBuilder.Entity("Core.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<int?>("TotalPriceCurrency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Core.Models.WishlistCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtCrop")
                        .HasColumnType("text");

                    b.Property<string>("BackImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("DesiredQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("ExactVersion")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsFoil")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<int?>("MinimumCondition")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OriginalDeckId")
                        .HasColumnType("integer");

                    b.Property<string>("ScryfallId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WishlistId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WishlistId");

                    b.ToTable("WishlistCards");
                });

            modelBuilder.Entity("Core.Models.BinderCard", b =>
                {
                    b.HasOne("Core.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.TradeBinder", "TradeBinder")
                        .WithMany("BinderCards")
                        .HasForeignKey("TradeBinderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("TradeBinder");
                });

            modelBuilder.Entity("Core.Models.Card", b =>
                {
                    b.HasOne("Core.Models.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Core.Models.Deck", b =>
                {
                    b.HasOne("Core.Models.DeckBranch", "CurrentBranch")
                        .WithMany()
                        .HasForeignKey("CurrentBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Models.DeckCommit", "CurrentCommit")
                        .WithMany()
                        .HasForeignKey("CurrentCommitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentBranch");

                    b.Navigation("CurrentCommit");
                });

            modelBuilder.Entity("Core.Models.DeckBranch", b =>
                {
                    b.HasOne("Core.Models.Deck", "Deck")
                        .WithMany("Branches")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.DeckCommit", "HeadCommit")
                        .WithMany()
                        .HasForeignKey("HeadCommitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deck");

                    b.Navigation("HeadCommit");
                });

            modelBuilder.Entity("Core.Models.DeckCard", b =>
                {
                    b.HasOne("Core.Models.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Card", "OwnedCard")
                        .WithMany()
                        .HasForeignKey("OwnedCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deck");

                    b.Navigation("OwnedCard");
                });

            modelBuilder.Entity("Core.Models.DeckCommit", b =>
                {
                    b.HasOne("Core.Models.Deck", "Deck")
                        .WithMany("Commits")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.DeckTree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("Core.Models.DeckCommitParent", b =>
                {
                    b.HasOne("Core.Models.DeckCommit", "Commit")
                        .WithMany("ParentLinks")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.DeckCommit", "ParentCommit")
                        .WithMany("ChildLinks")
                        .HasForeignKey("ParentCommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commit");

                    b.Navigation("ParentCommit");
                });

            modelBuilder.Entity("Core.Models.DeckTreeEntry", b =>
                {
                    b.HasOne("Core.Models.DeckTree", "Tree")
                        .WithMany("Entries")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("Core.Models.WishlistCard", b =>
                {
                    b.HasOne("Core.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistCards")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Core.Models.Deck", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Commits");

                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("Core.Models.DeckCommit", b =>
                {
                    b.Navigation("ChildLinks");

                    b.Navigation("ParentLinks");
                });

            modelBuilder.Entity("Core.Models.DeckTree", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Core.Models.TradeBinder", b =>
                {
                    b.Navigation("BinderCards");
                });

            modelBuilder.Entity("Core.Models.Wishlist", b =>
                {
                    b.Navigation("WishlistCards");
                });
#pragma warning restore 612, 618
        }
    }
}
