apiVersion: v1
kind: Secret
metadata:
  name: api-int-secrets
type: Opaque
stringData:
  connectionStringsDefault: 'Server=postgres-int;Port=5432;Database=main_int;User Id=root;Password={{ .Values.api.secrets.postgresPassword | default "" }};'
  jwtSecret: '{{ .Values.api.secrets.jwtSecret | default "" }}'
  googleClientId: '{{ .Values.api.secrets.googleClientId | default "" }}'
