{{- if .Values.api.config.manageAppsettingsConfigMap }}
{{- $settings := .Files.Get "files/appsettings.Integration.json" -}}
{{- $settings = required "Missing files/appsettings.Integration.json in chart" $settings -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-int-appsettings
data:
  appsettings.Integration.json: |
{{ $settings | indent 4 }}
{{- end }}
