{{- if .Values.api.persistence.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-int-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.persistence.logs.size }}
  storageClassName: {{ .Values.api.persistence.logs.storageClass }}
{{- end }}
{{- if and .Values.api.persistence.bulkData.enabled (not .Values.minio.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-int-bulk-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.api.persistence.bulkData.size }}
  storageClassName: {{ .Values.api.persistence.bulkData.storageClass }}
{{- end }}
