{{- if .Values.api.config.manageAppsettingsConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-int-appsettings
data:
  appsettings.Integration.json: |
{{- $settings := .Files.Get "files/appsettings.Integration.json" -}}
{{ required "Missing files/appsettings.Integration.json in chart" $settings | indent 4 }}
{{- end }}
