apiVersion: v1
kind: Service
metadata:
  name: api-int
spec:
  selector:
    app: api-int
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
  type: ClusterIP
