apiVersion: v1
kind: Secret
metadata:
  name: frontend-int-secrets
type: Opaque
stringData:
  expoPublicEnv: '{{ .Values.frontend.secrets.expoPublicEnv | default "" }}'
  expoPublicAppName: '{{ .Values.frontend.secrets.expoPublicAppName | default "" }}'
  expoPublicApiUrl: '{{ .Values.frontend.secrets.expoPublicApiUrl | default "" }}'
