apiVersion: v1
kind: Service
metadata:
  name: frontend-int
spec:
  selector:
    app: frontend-int
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  type: ClusterIP
