{{- if and .Values.kibana.enabled .Values.kibana.esToken }}
apiVersion: v1
kind: Secret
metadata:
  name: kibana-int-es-token
type: Opaque
stringData:
  token: {{ .Values.kibana.esToken | quote }}
{{- end }}
