{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.credentialsSecretName }}
  labels:
    app: minio-int
type: Opaque
stringData:
  {{ .Values.minio.credentialsAccessKeyKey }}: "{{ .Values.minio.accessKey | default "minioadmin" }}"
  {{ .Values.minio.credentialsSecretKeyKey }}: "{{ .Values.minio.secretKey | default "minioadminpassword" }}"
{{- end }}
