{{- if .Values.maintenance.restartCron.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtg-int-restart
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mtg-int-restart
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mtg-int-restart
subjects:
  - kind: ServiceAccount
    name: mtg-int-restart
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mtg-int-restart
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mtg-int-restart
spec:
  schedule: "{{ .Values.maintenance.restartCron.schedule }}"
  timeZone: "{{ .Values.maintenance.restartCron.timeZone }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mtg-int-restart
          restartPolicy: Never
          containers:
            - name: restart
              image: "{{ .Values.maintenance.restartCron.image }}"
              imagePullPolicy: IfNotPresent
              command:
                - kubectl
                - -n
                - {{ .Release.Namespace }}
                - rollout
                - restart
                - deployment
                - -l
                - app
{{- end }}
